services:
  pg-db:
    container_name: "postgres"
    build: ./db
    environment:
      POSTGRES_USER: $PG_DATABASE_USERNAME
      POSTGRES_PASSWORD: $PG_DATABASE_PASSWORD
      POSTGRES_DB: $PG_DATABASE
    restart: unless-stopped
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10

  otel-collector:
    container_name: "otel-collector"
    image: otel/opentelemetry-collector-contrib
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "4317:4317"  # OTLP gRPC receiver
      - "4318:4318"  # OTLP HTTP receiver
    environment:
      - AWS_REGION=$AWS_REGION
      - AWS_PROFILE=$AWS_PROFILE_NAME  # Change to real credentials for AWS
      - CLOUDWATCH_LOG_GROUP=$CLOUDWATCH_LOG_GROUP
      - CLOUDWATCH_LOG_STREAM=$CLOUDWATCH_LOG_STREAM
      - LOGS_API_ENDPOINT=$LOGS_API_ENDPOINT
      - TRACES_API_ENDPOINT=$TRACES_API_ENDPOINT
      - DATADOG_API_KEY=$DATADOG_API_KEY
      - DATADOG_API_URL=$DATADOG_API_URL
    volumes:
        - ./otel-collector/config.yaml:/etc/otel-collector-config.yaml
        - ~/.aws/credentials:/.aws/credentials  # AWS credentials

  file-delivery-service:
    build: ./rs
    container_name: "file-delivery-service"
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8080
      - LOG_LEVEL=$LOG_LEVEL
      - AUTH_DOMAIN=$AUTH_DOMAIN
      - AUTH_AUDIENCE=$AUTH_AUDIENCE
      - AWS_REGION=$AWS_REGION
      - AWS_PROFILE=$AWS_PROFILE_NAME
      - AWS_SHARED_CREDENTIALS_FILE=/.aws/credentials
      - AWS_S3_ENDPOINT=$AWS_S3_ENDPOINT
      - AWS_S3_STATEMENTS_BUCKET_NAME=$AWS_S3_STATEMENTS_BUCKET_NAME
      - AWS_S3_STATEMENTS_OBJECT_KEY_PREFIX=$AWS_S3_STATEMENTS_OBJECT_KEY_PREFIX
      - PG_DATABASE_URL=$PG_DATABASE_URL
      - PG_DATABASE_USERNAME=$PG_DATABASE_USERNAME
      - PG_DATABASE_PASSWORD=$PG_DATABASE_PASSWORD
      - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=$OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=$OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
      - OTEL_EXPORTER_OTLP_LOGS_ENDPOINT=$OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
      - OTEL_LOGS_EXPORTER=$OTEL_LOGS_EXPORTER
      - OTEL_METRICS_EXPORTER=$OTEL_METRICS_EXPORTER
      - OTEL_TRACES_EXPORTER=$OTEL_TRACES_EXPORTER
      - OTEL_RESOURCE_ATTRIBUTES=$OTEL_RESOURCE_ATTRIBUTES
    ports:
      - "8080:8080"
      - "5005:5005" # debugging
    depends_on:
      pg-db:
        condition: service_healthy
    volumes:
      - ~/.aws/credentials:/.aws/credentials  # AWS credentials
